## __Pandas__
---

Pandas is one of the **most important** libraries in Python — especially for **data science, data analysis, and machine learning**.

There are two main datatypes in pandas that we will cover later which are:

* * Serises - 1D
* * Dataframe - 2D

---

__🐼 **What Pandas Is Used For**__

Pandas is used to **work with data** in a fast, clean, and powerful way.

Think of it like **Excel on steroids** — but inside Python.

---

__✅ **1. Loading Data**__

Pandas makes it easy to bring data into Python:

* CSV files
* Excel files
* SQL databases
* JSON
* APIs

Example:

```python
df = pd.read_csv("data.csv")
```

---

__✅ **2. Cleaning Data (MOST IMPORTANT USE)**__

Pandas helps fix messy real-world data:

* Handle missing values
* Remove duplicates
* Convert data types
* Rename columns
* Filter rows
* Drop useless columns

Example:

```python
df.dropna()
df[df["age"] > 18]
```

---

__✅ **3. Analyzing Data**__

You can quickly compute:

* Minimum
* Maximum
* Mean
* Median
* Sum
* Count
* Group statistics

Example:

```python
df["salary"].mean()
df.groupby("gender")["score"].mean()
```

---

__✅ **4. Manipulating Data**__

Transform the shape of your data:

* Merge datasets
* Join tables
* Concatenate data
* Sort
* Reset index
* Pivot tables

Example:

```python
pd.merge(df1, df2, on="id")
```

---

__✅ **5. Exploring & Understanding Data**__

You can quickly inspect:

```python
df.head()
df.describe()
df.info()
```

---

__✅ **6. Exporting Data**__

Save data back out:

```python
df.to_csv("clean_data.csv")
```

---

__🧠 **In Simple Words**__

Pandas is used to:

**Load → Clean → Analyze → Transform → Export** data.

If NumPy is the engine…
**Pandas is the car you drive to get to your destination.**

---

In [2]:
#Importing pandas 
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.4

####  Series
A series is a pandas 1 dimensional lebled array that can hold any data type
Think of it like a single column in spreadsheet

In [3]:
data= [100, 102, 104, 106, 108, 110]

#Creating a Series from the given data
data_se = series = pd.Series(data, index=["a", "b", "c", "d", "e", "f"])
print(data_se)

a    100
b    102
c    104
d    106
e    108
f    110
dtype: int64

#### __Accessing values withing a series__
---
To access values or elements within a series we use the __loc__ attribute, which stands fro location.

__loc__ allows us to access values or elements through there index label

We can also access a value or element in a series using the __iloc__ attribute which stands for integer location.

__iloc__ allows us to access a value using the integer location which is the index of the value

In [4]:
#==================================================================================
#--------------------------------------using loc------------------------------------
#==================================================================================

#let's create a series that we will work with
#let's create Maths results for a certain class of seven students who have the following indexes
np.random.seed(7)
scores = np.random.randint(100, size=7)
print(scores)

maths_scores_se = pd.Series(scores, index = (101,102,103,104,105, 106,107))
print(maths_scores_se)

#Let's say we wanted to access the resuts of students with index:
#103
print(f"The student at index 103 scored {maths_scores_se.loc[103]}% in maths") #student at index 103

#105
print(f"The student at index 105 scored {maths_scores_se.loc[105]}% in maths") #marks for student at index 105

#=====================================================================================
#-----------------------------------using iloc----------------------------------------
#======================================================================================

# Index 0
print(f"The student at index 0 - 101 scored {maths_scores_se.iloc[0]}% in maths") #marks for student at index 0 - 101

# index 2
print(f"The student at index 2 - 103 scored {maths_scores_se.iloc[2]}% in maths") #marks for student at index 2 - 103

[47 68 25 67 83 23 92]
101    47
102    68
103    25
104    67
105    83
106    23
107    92
dtype: int64
The student at index 103 scored 25% in maths
The student at index 105 scored 83% in maths
The student at index 0 - 101 scored 47% in maths
The student at index 2 - 103 scored 25% in maths

#### __Updating values withing a series__
---
To update a value in a series we can use the __loc__ or __iloc__ to specify the value within a series that we want to update and update it.

In [5]:
print(maths_scores_se)

#Let's say we wanted to update index number 104, she got 75% in maths but we gave her 67%

maths_scores_se.loc[104] = 75
print(maths_scores_se)

#We can also use iloc
#maths_scores_se.iloc[3] = 75

101    47
102    68
103    25
104    67
105    83
106    23
107    92
dtype: int64
101    47
102    68
103    25
104    75
105    83
106    23
107    92
dtype: int64

#### __Filtering in series__
---
__filtering by values__

In [6]:
# Example 1
maths_scores_se
#Let's say from our data we want to filter out the students who who failed - the pass mark was 50%
print(f"This is the list of student who hit the pass mark, 50% and above:\n{maths_scores_se[maths_scores_se > 50]}\n")

#Let's say we wanted to identify the students who failed
print(f"This is the list of students who failed, 50% and below:\n{maths_scores_se[maths_scores_se < 50]}")

This is the list of student who hit the pass mark, 50% and above:
102    68
104    75
105    83
107    92
dtype: int64

This is the list of students who failed, 50% and below:
101    47
103    25
106    23
dtype: int64

In [7]:
#Example 2
data_filter = [150, 160, 170, 180, 190, 200]
series_filter = pd.Series(data_filter)
series_filter

#Filtering values greater than 170
print(series_filter[series_filter > 170])

3    180
4    190
5    200
dtype: int64

In [8]:
# creating a series from a dictionary

calories = {
    "Day1": 1750,
    "Day2": 2100,
    "Day3": 1700
}

calories_df = pd.Series(calories)
calories_df

#Accessing a value using its index label
#calories eten on day 1
print("Calories eaten on day 1: ",calories_df.loc["Day1"])


#Updating a value using its index label
#Updating calories eaten on day 2 to 2200
calories_df.loc["Day2"] = 2200
print("Updated calories eaten on day 2: ", calories_df.loc["Day2"])

#Filtering by values days where calories eaten are greater than 2000
highest_calories = calories_df[calories_df > 2000]
print("Days with calories eaten greater than 20000:\n" , highest_calories)

Calories eaten on day 1:  1750
Updated calories eaten on day 2:  2200
Days with calories eaten greater than 20000:
 Day2    2200
dtype: int64

In [9]:
# Exercices - create any series that comes in your mind and perform

weekly_sales = {
    "Week1": 5000,
    "week2": 7000,
    "week3": 6000,
    "week4": 8000
}

weekly_sales_se = pd.Series(weekly_sales)
print("Weekely sales series: \n", weekly_sales_se)

Weekely sales series:
 Week1    5000
week2    7000
week3    6000
week4    8000
dtype: int64

#### __Data frames__
---

In python, a datafram is a tabular data structures with rows and columns similar to excel only that this one is on steroids.

More often we will be working with data frames than series.

A data frame takes in a dictionary, whether nested or normal.
eg pd.Dataframe({})

__The anatomy of a dataframe__

1. On the left side of the dataframe we have the index, which start from 0

2. There are rows which are refferenced through __axis = 0__.

* * rows - __axis=0__

3. There are columns which are refferenced through __axis = 1__.

* * columns - __axis=1__

4. Then we have the data which can be of different data types

5. And lastly we have column names

In [10]:
# Let's create a class performance data frame of 6 subjects for a certain class

class_perfomance = {
    "English":[20, 60, 56, 78, 56, 79, 45, 90, 34, 59],
    "Kiswahili":[34, 56, 89, 53, 36, 67, 84, 35, 67, 45],
    "Maths":[90, 23, 45, 67, 84, 23, 60, 28, 84, 90],
    "Chemistry":[23, 56, 78, 56, 35, 96, 45, 34, 36, 78],
    "Phisics":[45, 67, 23, 56, 78, 90, 67, 75, 56, 83],
    "Computer":[70, 80, 80, 67, 48, 89, 96, 86, 84, 98]
    }

class_perfomance_df = pd.DataFrame(class_perfomance, index = range(101, 111))
class_perfomance_df

     English  Kiswahili  Maths  Chemistry  Phisics  Computer
101       20         34     90         23       45        70
102       60         56     23         56       67        80
103       56         89     45         78       23        80
104       78         53     67         56       56        67
105       56         36     84         35       78        48
106       79         67     23         96       90        89
107       45         84     60         45       67        96
108       90         35     28         34       75        86
109       34         67     84         36       56        84
110       59         45     90         78       83        98

In [11]:
sales ={
    "Weeks" : ["week1", "week2", "week3", "week4"],
    "Sales_amount" : [5000, 7000, 6000, 8000],
    "Expenses" : [2000, 2500, 2200, 3000],
    "Profit" : [3000, 4500, 3800, 5000],
    "Growth_percentage" : [10, 15, 12, 20]
}

sales_df = pd.DataFrame(sales, index = [101, 102, 103, 104])
sales_df

     Weeks  Sales_amount  Expenses  Profit  Growth_percentage
101  week1          5000      2000    3000                 10
102  week2          7000      2500    4500                 15
103  week3          6000      2200    3800                 12
104  week4          8000      3000    5000                 20

##### __Accessing data row wise__
---
We access data in a row using the __loc__ or __iloc__ attribute

In [12]:
# Accessing data for week 2 using loc - lebal indexing
print(f"This is the sales data for week 2:\n{sales_df.loc[102]}\n")

#Accessing data for week 3 using iloc - integer indexing
print(f"This is the sales data for week 3:\n{sales_df.iloc[2]}\n")

#we can also access multiple rows through nested lists and also do slicing 
#Let's access the performance for index 106, 108 and 110
print(f"This is the performance fo indexes 106, 108 and 110:\n{class_perfomance_df.loc[[106, 108, 110]]}\n")

print(f"This is the performance for students with indexes from 102 to 107:\n{class_perfomance_df.loc[102:107]}")

This is the sales data for week 2:
Weeks                week2
Sales_amount          7000
Expenses              2500
Profit                4500
Growth_percentage       15
Name: 102, dtype: object

This is the sales data for week 3:
Weeks                week3
Sales_amount          6000
Expenses              2200
Profit                3800
Growth_percentage       12
Name: 103, dtype: object

This is the performance fo indexes 106, 108 and 110:
     English  Kiswahili  Maths  Chemistry  Phisics  Computer
106       79         67     23         96       90        89
108       90         35     28         34       75        86
110       59         45     90         78       83        98

This is the performance for students with indexes from 102 to 107:
     English  Kiswahili  Maths  Chemistry  Phisics  Computer
102       60         56     23         56       67        80
103       56         89     45         78       23        80
104       78         53     67         56       56        67
105       56         36     84         35       78        48
106       79         67     23         96       90        89
107       45         84     60         45       67        96

#### __Accessing data column wise__
---

In [13]:
#let's view the expenses column in our sales data together with the weeks
print(f"This ara the total expenses over the week:\n{sales_df[["Weeks", "Expenses"]]}\n")

#let's see how the students performed in maths
print(f"This is the performance of the students in maths:\n{class_perfomance_df["Maths"]}\n")

This ara the total expenses over the week:
     Weeks  Expenses
101  week1      2000
102  week2      2500
103  week3      2200
104  week4      3000

This is the performance of the students in maths:
101    90
102    23
103    45
104    67
105    84
106    23
107    60
108    28
109    84
110    90
Name: Maths, dtype: int64

#### __Adding a new column__
---

In [14]:
#Let's add two more subjects, that is Geography and Biology
class_perfomance_df["Geography"] = [56, 70, 35, 46, 37, 63, 45, 23, 42, 53]
class_perfomance_df["Biology"] = [23, 78, 98, 65, 45, 65, 34, 67, 34, 21]
class_perfomance_df

,English,Kiswahili,Maths,Chemistry,Phisics,Computer,Geography,Biology
101,20,34,90,23,45,70,56,23
102,60,56,23,56,67,80,70,78
103,56,89,45,78,23,80,35,98
104,78,53,67,56,56,67,46,65
105,56,36,84,35,78,48,37,45
106,79,67,23,96,90,89,63,65
107,45,84,60,45,67,96,45,34
108,90,35,28,34,75,86,23,67
109,34,67,84,36,56,84,42,34
110,59,45,90,78,83,98,53,21

#### __Adding a row__
---
We can add a new row by concantenation, concating two dataframes

In [15]:
#Let's add ten more students in our performance data
additional_students = {"English":[23, 45, 67, 67, 86, 78, 34, 67, 89, 34],
                       "Kiswahili":[90, 24, 56, 45, 88, 45, 53, 56, 78, 90],
                       "Maths":[45, 67, 78, 45, 67, 45, 46, 48, 97, 89],
                       "Chemistry":[24, 35, 67, 57, 78, 45, 46, 34, 67, 78],
                       "Phisics":[45, 57, 56, 45, 35, 45, 78, 67, 67, 68],
                       "Computer":[25, 34, 56, 45, 78, 89, 67, 45, 78, 90],
                       "Geography":[45, 34, 35, 66, 45, 45, 77, 45, 56, 45],
                       "Biology":[23, 54, 65, 76, 45, 34, 35, 78, 34, 89]}

additional_students_pd = pd.DataFrame(additional_students, index = range(111, 121))
class_perfomance_df=pd.concat([class_perfomance_df, additional_students_pd])
class_perfomance_df

,English,Kiswahili,Maths,Chemistry,Phisics,Computer,Geography,Biology
101,20,34,90,23,45,70,56,23
102,60,56,23,56,67,80,70,78
103,56,89,45,78,23,80,35,98
104,78,53,67,56,56,67,46,65
105,56,36,84,35,78,48,37,45
106,79,67,23,96,90,89,63,65
107,45,84,60,45,67,96,45,34
108,90,35,28,34,75,86,23,67
109,34,67,84,36,56,84,42,34
110,59,45,90,78,83,98,53,21
111,23,90,45,24,45,25,45,23
112,45,24,67,35,57,34,34,54
113,67,56,78,67,56,56,35,65
114,67,45,45,57,45,45,66,76
115,86,88,67,78,35,78,45,45
116,78,45,45,45,45,89,45,34
117,34,53,46,46,78,67,77,35
118,67,56,48,34,67,45,45,78
119,89,78,97,67,67,78,56,34
120,34,90,89,78,68,90,45,89

#### __Importing CSV files and JSON files__
---
We import data eg CSVs and JSON files through:

* * __pd.read_csv("data.csv")__ - it will depend on the file we are importing

In [16]:
students = pd.read_csv("sample_students.csv", index_col="student_id")
students

             name  math_score  english_score  science_score
student_id
1           James          78             82             75
2            Mary          90             76             89
3           David          56             69             60
4           Sarah          88             91             95
5            John          92             85             88
6           Grace          67             74             70

In [17]:
financial_data_df = pd.read_csv("finance_data.csv", index_col="transaction_id")
financial_data_df

               account_type  amount transaction_type     status   client
transaction_id
1                    Credit    3153          Deposit     Failed    Sarah
2                   Savings    2770          Deposit     Failed     John
3                  Checking     661          Deposit  Completed    Sarah
4                   Savings    1450          Deposit    Pending    Alice
5                  Checking    4005         Transfer     Failed    Sarah
6                    Credit    4047         Transfer    Pending      Kim
7                  Checking    2977          Deposit     Failed    Sarah
8                   Savings    3613       Withdrawal  Completed    Alice
9                  Checking    4598          Deposit  Completed     John
10                  Savings    3514          Deposit     Failed    Alice
11                  Savings     206         Transfer     Failed    Sarah
12                 Checking    3184       Withdrawal    Pending  Michael
13                  Savings     978          Deposit     Failed     John
14                 Checking    2495         Transfer     Failed      Kim
15                  Savings    1710       Withdrawal    Pending    Sarah
16                  Savings     102         Transfer  Completed    Alice
17                  Savings    2185         Transfer  Completed    Alice
18                 Checking    3997         Transfer  Completed    Sarah
19                   Credit     838          Deposit     Failed    Alice
20                 Checking    1184         Transfer     Failed  Michael

In [18]:
sales_data_df = pd.read_csv("sales_data.csv")
sales_data_df

,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,1,Tablet,1989,8,Mombasa,James,15912
1,2,Headphones,403,7,Mombasa,James,2821
2,3,Tablet,1575,4,Kisumu,Brian,6300
3,4,Laptop,447,6,Nairobi,Brian,2682
4,5,Phone,637,5,Mombasa,James,3185
5,6,Laptop,453,4,Kisumu,Brian,1812
6,7,Laptop,1612,5,Kisumu,Mary,8060
7,8,Phone,834,7,Mombasa,Susan,5838
8,9,Laptop,923,7,Nairobi,Susan,6461
9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,11,Tablet,152,6,Nairobi,Brian,912
11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,13,Laptop,1345,2,Nakuru,Mary,2690
13,14,Tablet,878,3,Nakuru,Mary,2634
14,15,Laptop,736,6,Nairobi,Susan,4416
15,16,Tablet,1134,7,Nakuru,Brian,7938
16,17,Laptop,1108,7,Nakuru,Susan,7756
17,18,Camera,139,9,Kisumu,Mary,1251
18,19,Tablet,1240,6,Nairobi,James,7440
19,20,Tablet,481,2,Nairobi,Mary,962

#### __Exporting a dataframe__
---
Let's say we have cleaned our data and did some transformation and we wanted to export it to csv file.

We can do that through:

* * dataframe.to_csv("the name we want to give our exported file")

It is important to remember to include __index = False__ to avoid exporting the index as a column eg;

* __sales_data_df.to_csv("cleaned_sales_data.csv", index=False)__

In [19]:
#Let's export our sales data assuming we have done the cleaning and whatever
sales_data_df.to_csv("exrport_sample.csv")

In [20]:
sales = pd.read_csv("exrport_sample.csv")
sales

,Unnamed: 0,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,0,1,Tablet,1989,8,Mombasa,James,15912
1,1,2,Headphones,403,7,Mombasa,James,2821
2,2,3,Tablet,1575,4,Kisumu,Brian,6300
3,3,4,Laptop,447,6,Nairobi,Brian,2682
4,4,5,Phone,637,5,Mombasa,James,3185
5,5,6,Laptop,453,4,Kisumu,Brian,1812
6,6,7,Laptop,1612,5,Kisumu,Mary,8060
7,7,8,Phone,834,7,Mombasa,Susan,5838
8,8,9,Laptop,923,7,Nairobi,Susan,6461
9,9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,10,11,Tablet,152,6,Nairobi,Brian,912
11,11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,12,13,Laptop,1345,2,Nakuru,Mary,2690
13,13,14,Tablet,878,3,Nakuru,Mary,2634
14,14,15,Laptop,736,6,Nairobi,Susan,4416
15,15,16,Tablet,1134,7,Nakuru,Brian,7938
16,16,17,Laptop,1108,7,Nakuru,Susan,7756
17,17,18,Camera,139,9,Kisumu,Mary,1251
18,18,19,Tablet,1240,6,Nairobi,James,7440
19,19,20,Tablet,481,2,Nairobi,Mary,962

If you look at the example above, we exported the sales data with out indicating index is equal to false the it exported the the index as a column.

Here's how we fix it:

In [21]:
sales_data_df.to_csv("export_sample_2.csv", index=False)

In [22]:
pd.read_csv("export_sample_2.csv")

,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,1,Tablet,1989,8,Mombasa,James,15912
1,2,Headphones,403,7,Mombasa,James,2821
2,3,Tablet,1575,4,Kisumu,Brian,6300
3,4,Laptop,447,6,Nairobi,Brian,2682
4,5,Phone,637,5,Mombasa,James,3185
5,6,Laptop,453,4,Kisumu,Brian,1812
6,7,Laptop,1612,5,Kisumu,Mary,8060
7,8,Phone,834,7,Mombasa,Susan,5838
8,9,Laptop,923,7,Nairobi,Susan,6461
9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,11,Tablet,152,6,Nairobi,Brian,912
11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,13,Laptop,1345,2,Nakuru,Mary,2690
13,14,Tablet,878,3,Nakuru,Mary,2634
14,15,Laptop,736,6,Nairobi,Susan,4416
15,16,Tablet,1134,7,Nakuru,Brian,7938
16,17,Laptop,1108,7,Nakuru,Susan,7756
17,18,Camera,139,9,Kisumu,Mary,1251
18,19,Tablet,1240,6,Nairobi,James,7440
19,20,Tablet,481,2,Nairobi,Mary,962

#### __Describing data__
---
1. Describing data types in our data frame

We use the .dtypes attribute eg __dataframe.dtypes__

If you have noticed, the dtype has no parenthesis while the .to_csv has parenthesis at the end.
The reason is because, .dtype is an attribute - containing information about a particular thing eg data frame while the .to_csv() is a function which performs some task or operations eg calculations or conversion to a given file.

attribute - no parenthesis, function - has parenthesis

2. Displaying the columns in our dataframe through the .columns attribute:

* __dataframe.columns__

3. Displaying the indexes in our data through the .index attribute:

* __dataframe.index__

4. Using .decribe() function to describe our data

* __dataframe.describe()__ - gives us statistical operations about our numeric columns

__NB__ describe only works on numeric columns

5. Display information concerning our data using the .info() finction:

* __dataframe.info()__ - It gives us information of our data consisting of dtypes, index, columns etc.

6. There are also aggregation functions like mean, max, sum which we are going to cover later.

7. Lastly, the len function to get the length of out dataframe, number of rows:

* __len(dataframe)__

The reason we might want this is let's say our dataframe has 200, 000 rows and we wanted only to work on a few thousands for EDA, we can figure out the length of the dataframe we are working on by passing it on the len function

__These types of description function and attributes are some things that we might run through at the very start of exploring a new set of data to explore it and gain some information about it.__

In [23]:
# Let's look at the data types in our sales_data_df data frame
print(f"These are the data types in our sales data dataframe:\n{sales_data_df.dtypes}\n")

#Let's display the columns in our dataframe
print(f"These are the columns in our dataframe:\n{sales_data_df.columns}\n")

#Let's access the indexes in our finance dataframe
print(f"These are the indexes in our finances data:\n{financial_data_df.index}\n")

#Let's access for sales data
print(f"These are the index in our sales data:\n{sales_data_df.index}\n")

#Let's get a statiscal view of our data using the describe function
print(f"THis is the overal statistical analysis of our sales data data:\n{sales_data_df.describe()}\n")

#Let's see the information concerning our data
print(f"This is the information concerning our sales data:\n{sales_data_df.info()}\n")

#Let's see the length of our dataframe
print(f"Our sales data has {len(sales_data_df)} rows\n")

These are the data types in our sales data dataframe:
sale_id          int64
product         object
unit_price       int64
quantity         int64
region          object
sales_person    object
total_price      int64
dtype: object

These are the columns in our dataframe:
Index(['sale_id', 'product', 'unit_price', 'quantity', 'region',
       'sales_person', 'total_price'],
      dtype='object')

These are the indexes in our finances data:
Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype='int64', name='transaction_id')

These are the index in our sales data:
RangeIndex(start=0, stop=20, step=1)

THis is the overal statistical analysis of our sales data data:
        sale_id   unit_price   quantity   total_price
count  20.00000    20.000000  20.000000     20.000000
mean   10.50000   884.050000   5.450000   4750.150000
std     5.91608   499.663621   1.959457   3584.392282
min     1.00000   139.000000   2.000000    912.000000
25%     5.75000   474.000000   4.000000   2670.000000
50%    10.50000   856.000000   6.000000   3124.000000
75%    15.25000  1160.500000   7.000000   6705.750000
max    20.00000  1989.000000   9.000000  15912.000000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sale_id       20 non-null     int64
 1   product       20 non-null     object
 2   unit_price    20 non-null     int64
 3   quantity      20 non-null     int64
 4   region        20 non-null     object
 5   sales_person  20 non-null     object
 6   total_price   20 non-null     int64
dtypes: int64(4), object(3)
memory usage: 1.2+ KB
This is the information concerning our sales data:
None

Our sales data has 20 rows

#### __Viewing and selecting data__
---
* __dataframe.head()__ - This function returns the first 5 rows of our data

It gives us a quick snapshot of what our data contains

We can specify the number of rows we want it to print by passing the number of rows we want in the function

* * dataframe.head(15) - this will give us the first 15 rows of our data

* __dataframe.tail()__ - This function returns the last 5 rows of our data

Just as heae(), we can specify the number of rows we want.

* * dataframe.tail(15) - This returns the last 15 rows of our data.

In [24]:
#Selecting the  first 5 rows of our finance data
financial_data_df.head()

               account_type  amount transaction_type     status client
transaction_id
1                    Credit    3153          Deposit     Failed  Sarah
2                   Savings    2770          Deposit     Failed   John
3                  Checking     661          Deposit  Completed  Sarah
4                   Savings    1450          Deposit    Pending  Alice
5                  Checking    4005         Transfer     Failed  Sarah

In [25]:
#Let's select the first 15 rows of our finance data
financial_data_df.head(15)

               account_type  amount transaction_type     status   client
transaction_id
1                    Credit    3153          Deposit     Failed    Sarah
2                   Savings    2770          Deposit     Failed     John
3                  Checking     661          Deposit  Completed    Sarah
4                   Savings    1450          Deposit    Pending    Alice
5                  Checking    4005         Transfer     Failed    Sarah
6                    Credit    4047         Transfer    Pending      Kim
7                  Checking    2977          Deposit     Failed    Sarah
8                   Savings    3613       Withdrawal  Completed    Alice
9                  Checking    4598          Deposit  Completed     John
10                  Savings    3514          Deposit     Failed    Alice
11                  Savings     206         Transfer     Failed    Sarah
12                 Checking    3184       Withdrawal    Pending  Michael
13                  Savings     978          Deposit     Failed     John
14                 Checking    2495         Transfer     Failed      Kim
15                  Savings    1710       Withdrawal    Pending    Sarah

In [26]:
#selecting the first five rows of our product column in our sales data
sales_data_df["product"].head()

0        Tablet
1    Headphones
2        Tablet
3        Laptop
4         Phone
Name: product, dtype: object

In [27]:
#Let's select the last 5 rows of our finance data
financial_data_df.tail()

               account_type  amount transaction_type     status   client
transaction_id
16                  Savings     102         Transfer  Completed    Alice
17                  Savings    2185         Transfer  Completed    Alice
18                 Checking    3997         Transfer  Completed    Sarah
19                   Credit     838          Deposit     Failed    Alice
20                 Checking    1184         Transfer     Failed  Michael

In [28]:
#Let's select the last 15 rows of our finance data
financial_data_df.tail(15)

               account_type  amount transaction_type     status   client
transaction_id
6                    Credit    4047         Transfer    Pending      Kim
7                  Checking    2977          Deposit     Failed    Sarah
8                   Savings    3613       Withdrawal  Completed    Alice
9                  Checking    4598          Deposit  Completed     John
10                  Savings    3514          Deposit     Failed    Alice
11                  Savings     206         Transfer     Failed    Sarah
12                 Checking    3184       Withdrawal    Pending  Michael
13                  Savings     978          Deposit     Failed     John
14                 Checking    2495         Transfer     Failed      Kim
15                  Savings    1710       Withdrawal    Pending    Sarah
16                  Savings     102         Transfer  Completed    Alice
17                  Savings    2185         Transfer  Completed    Alice
18                 Checking    3997         Transfer  Completed    Sarah
19                   Credit     838          Deposit     Failed    Alice
20                 Checking    1184         Transfer     Failed  Michael

In [29]:
# Let's select the last 10 rows for columns account_type and amount in finance data.
financial_data_df[["account_type", "amount"]].tail(10)

               account_type  amount
transaction_id
11                  Savings     206
12                 Checking    3184
13                  Savings     978
14                 Checking    2495
15                  Savings    1710
16                  Savings     102
17                  Savings    2185
18                 Checking    3997
19                   Credit     838
20                 Checking    1184

#### __Selecting rows and columns - combined__
---
We covered selecting rows and and columns individually, now let's cover selecting rows and columns combined. 

when selecting rows and columns combined, we use the __loc__ or __iloc__ attribute.

syntax:

* * dataframe.loc[row_location(s), column_name(s)] - when you have more then one column, you place it inside a list. Same applies for rows

* * dataframe.iloc[row_index(s), column_name(s)] - when you have more then one column, you place it inside a list. Same applies for rows

In [30]:
financial_data_df.head()

#Let's select the client with transaction_id 10 and only select the client column to get his name only
print(f"The name of the client with transaction id 10 is, {financial_data_df.loc[10, "client"]}\n")

#Let's select the same client this time, let's the client name and account_type 
print(financial_data_df.loc[10, ["client", "account_type"]])

#Let's select clients at index 12, 5, and 19, and columns, amount, transaction type, status and client
print(f"\n{financial_data_df.loc[[5, 12, 19], "amount":]}") #I have selected a range of columns upto the end

#Let,s try iloc now - as we know iloc works with the index, that is from 0 to the last row which is the last index
#Let's select the cliet at index 5 and 10, with columns client and account type
print(f"\n{financial_data_df.iloc[[5, 10], [0, -1]]}")

#Let's select clients from index 5 to 10, with columns client and transaction_type
print(f"\n{financial_data_df.iloc[5:11, [0, -1]]}")

#Last one, index 10, with columns amount, transaction_type, status and client
print(f"\n{financial_data_df.iloc[10, 1:]}")

The name of the client with transaction id 10 is, Alice

client            Alice
account_type    Savings
Name: 10, dtype: object

                amount transaction_type   status   client
transaction_id
5                 4005         Transfer   Failed    Sarah
12                3184       Withdrawal  Pending  Michael
19                 838          Deposit   Failed    Alice

               account_type client
transaction_id
6                    Credit    Kim
11                  Savings  Sarah

               account_type client
transaction_id
6                    Credit    Kim
7                  Checking  Sarah
8                   Savings  Alice
9                  Checking   John
10                  Savings  Alice
11                  Savings  Sarah

amount                   206
transaction_type    Transfer
status                Failed
client                 Sarah
Name: 11, dtype: object

#### __Summury__
---

__1️⃣ Single Column vs Multiple Columns in `.iloc`__

* * Selecting a single column

```python
df.iloc[0, 1]  # first row, second column
```

* **No list needed** for a single column.
* Returns a **scalar value** (a single item).


* * Selecting a range of columns 

```python
df.iloc[0, 0:2]  # first row, columns 0 and 1
```

* You **don’t use a nested list** for a slice.
* `0:2` is a **slice object**, not a list.
* Returns a **Series** with the selected columns.

* * Selecting multiple specific columns (non-consecutive)

```python
df.iloc[0, [0, 2]]  # first row, columns 0 and 2
```

* Now you **do need a list** because these are discrete positions, not a continuous slice.
* Returns a **Series** with the selected columns.

---

✅ **Rule of Thumb**

| Selection Type                  | Syntax              | Use List? | Returns |
| ------------------------------- | ------------------- | --------- | ------- |
| Single column                   | `df.iloc[0, 1]`     | ❌         | Scalar  |
| Continuous range of columns     | `df.iloc[0, 0:3]`   | ❌         | Series  |
| Non-continuous/multiple columns | `df.iloc[0, [0,2]]` | ✅         | Series  |

**The same concept applies to loc as well!!!**

---

#### **Filtering using pandas**
---

In [31]:
#Let's filter out our data to be left with laptopts alone
laptops = sales_data_df[sales_data_df["product"] == "Laptop"]
laptops

    sale_id product  unit_price  quantity   region sales_person  total_price
3         4  Laptop         447         6  Nairobi        Brian         2682
5         6  Laptop         453         4   Kisumu        Brian         1812
6         7  Laptop        1612         5   Kisumu         Mary         8060
8         9  Laptop         923         7  Nairobi        Susan         6461
11       12  Laptop         574         5   Nakuru       Kelvin         2870
12       13  Laptop        1345         2   Nakuru         Mary         2690
14       15  Laptop         736         6  Nairobi        Susan         4416
16       17  Laptop        1108         7   Nakuru        Susan         7756

In [32]:
#Let's select amounts in our finance data that are greater than or eaqual to 2000
financial_data_df[financial_data_df["amount"] >= 2000]

               account_type  amount transaction_type     status   client
transaction_id
1                    Credit    3153          Deposit     Failed    Sarah
2                   Savings    2770          Deposit     Failed     John
5                  Checking    4005         Transfer     Failed    Sarah
6                    Credit    4047         Transfer    Pending      Kim
7                  Checking    2977          Deposit     Failed    Sarah
8                   Savings    3613       Withdrawal  Completed    Alice
9                  Checking    4598          Deposit  Completed     John
10                  Savings    3514          Deposit     Failed    Alice
12                 Checking    3184       Withdrawal    Pending  Michael
14                 Checking    2495         Transfer     Failed      Kim
17                  Savings    2185         Transfer  Completed    Alice
18                 Checking    3997         Transfer  Completed    Sarah

In [33]:
#Let's select laptops costing 2000 plus
sales_data_df[(sales_data_df["product"] == "Laptop") & (sales_data_df["total_price"] >= 2000)]

#The parenthesis enclosing each filter are very important, without them you may get errors or nothing as the output without one

    sale_id product  unit_price  quantity   region sales_person  total_price
3         4  Laptop         447         6  Nairobi        Brian         2682
6         7  Laptop        1612         5   Kisumu         Mary         8060
8         9  Laptop         923         7  Nairobi        Susan         6461
11       12  Laptop         574         5   Nakuru       Kelvin         2870
12       13  Laptop        1345         2   Nakuru         Mary         2690
14       15  Laptop         736         6  Nairobi        Susan         4416
16       17  Laptop        1108         7   Nakuru        Susan         7756

In [34]:
#Let's display people with a credit of more than 2500 from our financial data
financial_data_df[
    (financial_data_df["account_type"]=="Credit") &
    (financial_data_df["amount"] > 2500)
    ]

               account_type  amount transaction_type   status client
transaction_id
1                    Credit    3153          Deposit   Failed  Sarah
6                    Credit    4047         Transfer  Pending    Kim


#### **Aggregate functions**
---
We use aggregate functions to analyzing our Data

You can perform the following operations using aggregate functions:

* Minimum
* Maximum
* Mean
* Median
* Sum
* Count
* Group statistics

We can perform aggregate operations either in our whole data frame or individual columns.

#### **Aggregates for a whole data frame**
---
Let's do some examples:

In [37]:
#Agregating our data

#mean
print(f"These are the mean operations of our entire sales data:\n{sales_data_df.mean(numeric_only=True)}\n")
#We use numeric_only = True to avoid getting errors as our data contains text which can't be aggregated

#sum
print(f"These are the sum operations of our entire sales data:\n{sales_data_df.sum(numeric_only=True)}\n")

#min
print(f"These are the minimum values in our sales data\n{sales_data_df.min(numeric_only=True)}\n")

#max
print(f"These are the maximum values in our sales data:\n{sales_data_df.max(numeric_only=True)}\n")

#count()
print(f"These are the total number of entries in our finance data:\n{financial_data_df.count()}")
#For count we don't need to specify numeric columns only as the text can also be counted

These are the mean operations of our entire sales data:
sale_id          10.50
unit_price      884.05
quantity          5.45
total_price    4750.15
dtype: float64

These are the sum operations of our entire sales data:
sale_id          210
unit_price     17681
quantity         109
total_price    95003
dtype: int64

These are the minimum values in our sales data
sale_id          1
unit_price     139
quantity         2
total_price    912
dtype: int64

These are the maximum values in our sales data:
sale_id           20
unit_price      1989
quantity           9
total_price    15912
dtype: int64

These are the total number of entries in our finance data:
account_type        20
amount              20
transaction_type    20
status              20
client              20
dtype: int64

#### **Aggregates for a single column**
---
Let's do some code examples:

In [38]:
#Let's calculated the sum, mean, max, min and count operation on our finance data in the amiunt column
#Sum
print(f"The total of the amount in our finance data is:-\n {financial_data_df["amount"].sum()}\n")

#Mean
print(f"The mean of the amount in our finance data is:-\n {financial_data_df["amount"].mean()}\n")

#max
print(f"The maximum amount in our finance data is:- \n {financial_data_df["amount"].max()}\n")

#min
print(f"The minimum amount in our finance data is:-\n {financial_data_df["amount"].min()}\n")

#count
print(f"The total number of amount in our finance data is:- \n {financial_data_df["amount"].count()}\n")

#Instead of having to type everything independently we can simply calculate everything in a singl code like in below
print(f"This is a summary statistics of the total price of the products in our sales data:\n{sales_data_df["total_price"].agg(
    ["sum", "mean", "max", "min", "count"])}\n")

#Let's get the sum, mean, max and min of the unit price and total price column
sales_data_df[["unit_price", "total_price"]].agg(["sum", "mean", "max", "min"])

The total of the amount in our finance data is:-
 47667

The mean of the amount in our finance data is:-
 2383.35

The maximum amount in our finance data is:-
 4598

The minimum amount in our finance data is:-
 102

The total number of amount in our finance data is:-
 20

This is a summary statistics of the total price of the products in our sales data:
sum      95003.00
mean      4750.15
max      15912.00
min        912.00
count       20.00
Name: total_price, dtype: float64

      unit_price  total_price
sum     17681.00     95003.00
mean      884.05      4750.15
max      1989.00     15912.00
min       139.00       912.00

#### **Group by**
---

GroupBy is one of the most **powerful**, **important**, and **beautiful** concepts in Pandas — once you understand it, data analysis becomes 10× easier.

Let’s break it down **very simply**.

⭐ **What is `groupby()`?**

`groupby()` means:

* __1️⃣ Split the Data__

Divide your DataFrame into groups based on a column (or multiple columns).

* __2️⃣ Apply an operation__

For each group, run something like:

* sum
* mean
* count
* min
* max
* std (standard deviation)
* custom function

* __3️⃣ Combine the results__

Return a new DataFrame with the aggregated information.

Pandas does all 3 steps in the background.

📦 **Simple Example**

Say you have sales data:

| product | region  | sales |
| ------- | ------- | ----- |
| Phone   | Nairobi | 3000  |
| Tablet  | Mombasa | 2500  |
| Phone   | Kisumu  | 2800  |
| Tablet  | Nairobi | 2600  |

If you want **total sales per product**, you do:

```python
df.groupby("product")["sales"].sum()
```

Result:

| product | sales |
| ------- | ----- |
| Phone   | 5800  |
| Tablet  | 5100  |

🔥 **Why GroupBy Exists**

Because datasets usually contain:

* many repeated categories
* many repeated regions
* many repeated customers
* many repeated dates

GroupBy lets you **summarize** them.

🎯 **Most Common Uses**

* ➡️ Count how many times each value appears

```python
df.groupby("region")["sales"].count()
```

* ➡️ Average sales in each region

```python
df.groupby("region")["sales"].mean()
```

* ➡️ Summaries for multiple columns

```python
df.groupby("region")[["sales", "quantity"]].sum()
```

* ➡️ Group by multiple columns**

```python
df.groupby(["region", "product"])["sales"].sum()
```

This gives you a pivot-table-like output.

🧠 **Think of it like this:**

If your DataFrame was a classroom:

* `groupby("gender")` = group boys together and girls together
* apply mean → get average score for boys, average score for girls

🏁 **In Summary**

`groupby()` is for:

🔹 Splitting
🔹 Aggregating
🔹 Combining

It helps you turn messy, repetitive data into summarized insights.

We can perform group by on the whole dataframe or individual columns

#### **Group by aggregation - whole dataframe**
---

In [39]:
#Let's group our financial data by acount type and find the sum, mean, max, min, and count
print(f"The sum of our financial data grouped by account type is:\n{financial_data_df.groupby(
    "account_type").sum(numeric_only=True)}\n")

print(f"The mean of our financial data grouped by account type is:\n{financial_data_df.groupby(
    "account_type").mean(numeric_only=True)}\n")

print(f"The maximum amount in our financial data grouped by account type is:\n{financial_data_df.groupby(
    "account_type").max(numeric_only=True)}\n")

print(f"The minimum amount in our financial data grouped by account type is:\n{financial_data_df.groupby(
    "account_type").min(numeric_only=True)}")

print(f"The total count of our finance data is:\n{financial_data_df.groupby(
    "account_type").count()}\n")

The sum of our financial data grouped by account type is:
              amount
account_type
Checking       23101
Credit          8038
Savings        16528

The mean of our financial data grouped by account type is:
                   amount
account_type
Checking      2887.625000
Credit        2679.333333
Savings       1836.444444

The maximum amount in our financial data grouped by account type is:
              amount
account_type
Checking        4598
Credit          4047
Savings         3613

The minimum amount in our financial data grouped by account type is:
              amount
account_type
Checking         661
Credit           838
Savings          102
The total count of our finance data is:
              amount  transaction_type  status  client
account_type
Checking           8                 8       8       8
Credit             3                 3       3       3
Savings            9                 9       9       9

In [40]:
# Let's group our sales data by region and product
print(f"Th sum of our whole sales data grouped by region and product is:\n{sales_data_df.groupby([
    "region", 
    "product"
    ]).sum(numeric_only=True)}\n")

print(f"The mean of our whole sales data grouped by region and product is:\n{sales_data_df.groupby([
    "region", 
    "product"
    ]).mean(numeric_only=True)}\n")

print(f"The maximum values in our sales data grouped by region and product is:\n{sales_data_df.groupby([
    "region", 
    "product"
    ]).max(numeric_only=True)}\n")

print(f"The minimum values in our sales data grouped by region and product is:\n{sales_data_df.groupby([
    "region", 
    "product"
    ]).min(numeric_only=True)}\n")

print(f"The total count of our sales data grouped by region and product is:\n{sales_data_df.groupby([
    "region", 
    "product"
    ]).count()}\n")

Th sum of our whole sales data grouped by region and product is:
                    sale_id  unit_price  quantity  total_price
region  product
Kisumu  Camera           18         139         9         1251
        Laptop           13        2065         9         9872
        Tablet            3        1575         4         6300
Mombasa Camera           10        1021         3         3063
        Headphones        2         403         7         2821
        Phone            13        1471        12         9023
        Tablet            1        1989         8        15912
Nairobi Laptop           28        2106        19        13559
        Tablet           50        1873        14         9314
Nakuru  Laptop           42        3027        14        13316
        Tablet           30        2012        10        10572

The mean of our whole sales data grouped by region and product is:
                      sale_id   unit_price  quantity   total_price
region  product
Kisumu  Camera      18.000000   139.000000  9.000000   1251.000000
        Laptop       6.500000  1032.500000  4.500000   4936.000000
        Tablet       3.000000  1575.000000  4.000000   6300.000000
Mombasa Camera      10.000000  1021.000000  3.000000   3063.000000
        Headphones   2.000000   403.000000  7.000000   2821.000000
        Phone        6.500000   735.500000  6.000000   4511.500000
        Tablet       1.000000  1989.000000  8.000000  15912.000000
Nairobi Laptop       9.333333   702.000000  6.333333   4519.666667
        Tablet      16.666667   624.333333  4.666667   3104.666667
Nakuru  Laptop      14.000000  1009.000000  4.666667   4438.666667
        Tablet      15.000000  1006.000000  5.000000   5286.000000

The maximum values in our sales data grouped by region and product is:
                    sale_id  unit_price  quantity  total_price
region  product
Kisumu  Camera           18         139         9         1251
        Laptop            7        1612         5         8060
        Tablet            3        1575         4         6300
Mombasa Camera           10        1021         3         3063
        Headphones        2         403         7         2821
        Phone             8         834         7         5838
        Tablet            1        1989         8        15912
Nairobi Laptop           15         923         7         6461
        Tablet           20        1240         6         7440
Nakuru  Laptop           17        1345         7         7756
        Tablet           16        1134         7         7938

The minimum values in our sales data grouped by region and product is:
                    sale_id  unit_price  quantity  total_price
region  product
Kisumu  Camera           18         139         9         1251
        Laptop            6         453         4         1812
        Tablet            3        1575         4         6300
Mombasa Camera           10        1021         3         3063
        Headphones        2         403         7         2821
        Phone             5         637         5         3185
        Tablet            1        1989         8        15912
Nairobi Laptop            4         447         6         2682
        Tablet           11         152         2          912
Nakuru  Laptop           12         574         2         2690
        Tablet           14         878         3         2634

The total count of our sales data grouped by region and product is:
                    sale_id  unit_price  quantity  sales_person  total_price
region  product
Kisumu  Camera            1           1         1             1            1
        Laptop            2           2         2             2            2
        Tablet            1           1         1             1            1
Mombasa Camera            1           1         1             1            1
        Headphones        1           1         1             1            1
        Phone             2           2         2             2            2
        Tablet            1           1         1             1            1
Nairobi Laptop            3           3         3             3            3
        Tablet            3           3         3             3            3
Nakuru  Laptop            3           3         3             3            3
        Tablet            2           2         2             2            2

#### **Grouping by aggregation - individual column**
---

In [41]:
#Let's group our finance data by account and then aggregate the amount column
#Let's frist get the sum alone
print(f"This is the sum of the amount in our financial data grouped by account type:\n{financial_data_df.groupby(
    "account_type")["amount"].sum()}\n")

#now i want us to get the mean, max, min and count
print(f"This is a summary statitstics of the amount in our financial data grouped by account type:\n{financial_data_df.groupby(
    "account_type")["amount"].agg(["mean", "max", "min", "count"])}\n")

This is the sum of the amount in our financial data grouped by account type:
account_type
Checking    23101
Credit       8038
Savings     16528
Name: amount, dtype: int64

This is a summary statitstics of the amount in our financial data grouped by account type:
                     mean   max  min  count
account_type
Checking      2887.625000  4598  661      8
Credit        2679.333333  4047  838      3
Savings       1836.444444  3613  102      9

In [42]:
#Let's group our sales data by region and product and then aggregate the unit price and total price

#We will start first of all by geting the sum
print(f"This is the sum of the unit price and total price of our sales data grouped by region & product:\n{sales_data_df.groupby([
    "region", "product"])[["unit_price", "total_price"]].sum()}\n")

#now let's find the mean. max, min and count
print(f"This is the statistical analysis of our sale data grouped by region and product:\n{sales_data_df.groupby(["region", "product"])[[
    "unit_price", "total_price"]].agg(["mean", "max", "min", "count"])}\n")

This is the sum of the unit price and total price of our sales data grouped by region & product:
                    unit_price  total_price
region  product
Kisumu  Camera             139         1251
        Laptop            2065         9872
        Tablet            1575         6300
Mombasa Camera            1021         3063
        Headphones         403         2821
        Phone             1471         9023
        Tablet            1989        15912
Nairobi Laptop            2106        13559
        Tablet            1873         9314
Nakuru  Laptop            3027        13316
        Tablet            2012        10572

This is the statistical analysis of our sale data grouped by region and product:
                     unit_price                     total_price                \
                           mean   max   min count          mean    max    min
region  product
Kisumu  Camera       139.000000   139   139     1   1251.000000   1251   1251
        Laptop      1032.500000  1612   453     2   4936.000000   8060   1812
        Tablet      1575.000000  1575  1575     1   6300.000000   6300   6300
Mombasa Camera      1021.000000  1021  1021     1   3063.000000   3063   3063
        Headphones   403.000000   403   403     1   2821.000000   2821   2821
        Phone        735.500000   834   637     2   4511.500000   5838   3185
        Tablet      1989.000000  1989  1989     1  15912.000000  15912  15912
Nairobi Laptop       702.000000   923   447     3   4519.666667   6461   2682
        Tablet       624.333333  1240   152     3   3104.666667   7440    912
Nakuru  Laptop      1009.000000  1345   574     3   4438.666667   7756   2690
        Tablet      1006.000000  1134   878     2   5286.000000   7938   2634


                   count
region  product
Kisumu  Camera         1
        Laptop         2
        Tablet         1
Mombasa Camera         1
        Headphones     1
        Phone          2
        Tablet         1
Nairobi Laptop         3
        Tablet         3
Nakuru  Laptop         3
        Tablet         2

In [43]:
# Let's group by the whole dataframe
sales_data_df.groupby(["product", "region"]).agg(
    "mean", "sum"
)
sales_data_df

,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,1,Tablet,1989,8,Mombasa,James,15912
1,2,Headphones,403,7,Mombasa,James,2821
2,3,Tablet,1575,4,Kisumu,Brian,6300
3,4,Laptop,447,6,Nairobi,Brian,2682
4,5,Phone,637,5,Mombasa,James,3185
5,6,Laptop,453,4,Kisumu,Brian,1812
6,7,Laptop,1612,5,Kisumu,Mary,8060
7,8,Phone,834,7,Mombasa,Susan,5838
8,9,Laptop,923,7,Nairobi,Susan,6461
9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,11,Tablet,152,6,Nairobi,Brian,912
11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,13,Laptop,1345,2,Nakuru,Mary,2690
13,14,Tablet,878,3,Nakuru,Mary,2634
14,15,Laptop,736,6,Nairobi,Susan,4416
15,16,Tablet,1134,7,Nakuru,Brian,7938
16,17,Laptop,1108,7,Nakuru,Susan,7756
17,18,Camera,139,9,Kisumu,Mary,1251
18,19,Tablet,1240,6,Nairobi,James,7440
19,20,Tablet,481,2,Nairobi,Mary,962

#### **Data cleaning**
---

Data cleaning is the process of fixing/remoing incomplete. incorrect, or irrelevant data.

**~75% of the work done with pandas is data cleaning**

In [44]:
# let's load our messy data
messy_finance_data = pd.read_csv("finance_data_messy.csv", index_col="transaction_id")

# Let's look into our data
print(messy_finance_data.info())

#Let's see the length of our data
print(f"\nTotal rows:\n{len(messy_finance_data)}\n")

#Let's print out the columns
print(f"Columns:\n{messy_finance_data.columns}")


#To print out the entire data, we can print it out through the to_string function
# print(messy_finance_data.to_string())

#Let's view our data - python automatically gives us the first 5 and the last 5
messy_finance_data

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 162 to 856
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account_type      737 non-null    object
 1   amount            813 non-null    float64
 2   transaction_type  682 non-null    object
 3   status            877 non-null    object
 4   client            859 non-null    object
 5   timestamp         616 non-null    object
dtypes: float64(1), object(5)
memory usage: 65.6+ KB
None

Total rows:
1200

Columns:
Index(['account_type', 'amount', 'transaction_type', 'status', 'client',
       'timestamp'],
      dtype='object')

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
162,NaN,4500.0,NaN,NaN,John,NaN
579,Checking,200.0,NaN,NaN,Alice,Invalid
712,Credit,NaN,NaN,Completed,NaN,NaN
543,Savings,200.0,NaN,Pending,Michael,NaN
587,Checking,200.0,NaN,Pending,Kim,NaN
...,...,...,...,...,...,...
344,Credit,NaN,NaN,Pending,Kim,Invalid
262,Credit,3000.0,Withdrawal,Pending,Kim,NaN
283,NaN,200.0,Transfer,Failed,Michael,NaN
850,Savings,NaN,Transfer,Failed,Michael,Invalid
856,NaN,4500.0,NaN,Pending,NaN,2025-02-01

In [45]:
# Let's load our sales messy data
messy_sales_data = pd.read_csv("sales_data_messy.csv", index_col="sale_id")

#Let's look into our data
print(messy_sales_data.info())

#Let's print out the size of our data
print(f"\nTotal rows:\n{len(messy_sales_data)}\n")

#Let's print out the columns
print(f"Columns:\n{messy_sales_data.columns}\n")

#let's view our data
messy_sales_data

<class 'pandas.core.frame.DataFrame'>
Index: 1200 entries, 103 to 47
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product       866 non-null    object
 1   unit_price    1035 non-null   float64
 2   quantity      1011 non-null   float64
 3   region        796 non-null    object
 4   sales_person  996 non-null    object
 5   date          715 non-null    object
 6   total_price   876 non-null    float64
dtypes: float64(3), object(4)
memory usage: 75.0+ KB
None

Total rows:
1200

Columns:
Index(['product', 'unit_price', 'quantity', 'region', 'sales_person', 'date',
       'total_price'],
      dtype='object')

,product,unit_price,quantity,region,sales_person,date,total_price
sale_id,,,,,,,
103,Headphones,1200.0,2.0,Kisumu,Brian,2025-01-01,2400.0
436,Headphones,150.0,NaN,NaN,Kelvin,NaN,NaN
271,Camera,NaN,3.0,Nairobi,Mary,2025-01-05,NaN
107,Phone,NaN,4.0,NaN,Kelvin,NaN,NaN
72,Tablet,100.0,4.0,Kisumu,James,NaN,400.0
...,...,...,...,...,...,...,...
157,NaN,150.0,NaN,Mombasa,NaN,Not Available,NaN
648,Laptop,500.0,NaN,Nakuru,James,NaN,NaN
261,Headphones,NaN,5.0,Mombasa,Kelvin,2025-01-05,NaN
157,Tablet,150.0,1.0,Kisumu,Mary,2025-01-05,150.0
47,Laptop,1200.0,3.0,Kisumu,Mary,NaN,3600.0

#### **Handling missing values**
---
1. __Droping rows with missing values - on individual columns__
---

We use the **dropna(subset=column)** to drop rows with missing values

In [46]:
#Cleaning the messy finance data
#We will start by droping rows in individual columns in our data

#Let's start with the client column
print(f"{messy_finance_data.dropna(subset="client",inplace=False).head()}\n")
#By default, inplace is always false but for the purporse of learning i have indicated it manually
#With inplace as false, our original dat won't be altered or modified by the opearation

#Let's perform dropna on multiple columns - transaction id, transaction type and status
messy_finance_data.dropna(subset= ["account_type", "transaction_type", "status"], inplace=False).head(15)

               account_type  amount transaction_type   status   client  \
transaction_id
162                     NaN  4500.0              NaN      NaN     John
579                Checking   200.0              NaN      NaN    Alice
543                 Savings   200.0              NaN  Pending  Michael
587                Checking   200.0              NaN  Pending      Kim
237                     NaN  4500.0              NaN  Pending    Sarah

               timestamp
transaction_id
162                  NaN
579              Invalid
543                  NaN
587                  NaN
237                  NaN

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
532,Checking,NaN,Transfer,Pending,Alice,2025-02-01
464,Credit,200.0,Transfer,Pending,Michael,NaN
551,Checking,3000.0,Transfer,Completed,Kim,NaN
326,Checking,NaN,Deposit,Completed,NaN,NaN
91,Checking,200.0,Deposit,Failed,John,Invalid
601,Savings,4500.0,Transfer,Completed,Kim,Invalid
764,Checking,200.0,Withdrawal,Completed,Sarah,2025-02-01
239,Checking,200.0,Withdrawal,Pending,NaN,Invalid
805,Credit,100.0,Transfer,Failed,Michael,NaN
755,Checking,200.0,Deposit,Pending,Alice,2025-02-01
479,Checking,3000.0,Withdrawal,Failed,Michael,2025-02-01
682,Credit,NaN,Withdrawal,Pending,NaN,NaN
82,Checking,4500.0,Withdrawal,Completed,Kim,NaN
163,Savings,3000.0,Transfer,Failed,Sarah,NaN
827,Credit,3000.0,Transfer,Failed,NaN,NaN

2. **Droping rows with missing values - on the entire dataframe**
---
We use **dropna()** function to drop rows with missing values on our entire dataframe

In [47]:
#Let's drop missing values on our entire data frame and stor it in another varaible called clean financial data
messy_finance_data.dropna(inplace=True)
messy_finance_data

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
91,Checking,200.0,Deposit,Failed,John,Invalid
601,Savings,4500.0,Transfer,Completed,Kim,Invalid
764,Checking,200.0,Withdrawal,Completed,Sarah,2025-02-01
755,Checking,200.0,Deposit,Pending,Alice,2025-02-01
479,Checking,3000.0,Withdrawal,Failed,Michael,2025-02-01
...,...,...,...,...,...,...
151,Savings,3000.0,Transfer,Completed,Michael,Invalid
419,Checking,4500.0,Withdrawal,Failed,Kim,Invalid
226,Credit,200.0,Withdrawal,Completed,Sarah,Invalid
12,Credit,4500.0,Deposit,Failed,Michael,2025-02-01
158,Savings,3000.0,Withdrawal,Pending,Kim,Invalid

#### **Replacing missing values**
---
1. **Replacing missing vales - on individual columns**
---
We use the **fillna({"column_name":"replacement"})** to replace missing values on individual columns

In [48]:
#Let's replace the missing values in the total price column with "None", with the hope that they are going to be added later
print(f"{messy_sales_data.fillna({"total_price":"None"}, inplace=False).head(10)}\n")
#By default, inplace is always false but for the purporse of learning i have indicated it manually
#With inplace as false, our original dat won't be altered or modified by the opearation

#Let's replace the missing values in product, unit price, region and date with "None"
messy_sales_data.fillna({"product":"None", "unit_price":"None", "region":"None", "date":"None"}, inplace=False).head(15)

            product  unit_price  quantity   region sales_person        date  \
sale_id
103      Headphones      1200.0       2.0   Kisumu        Brian  2025-01-01
436      Headphones       150.0       NaN      NaN       Kelvin         NaN
271          Camera         NaN       3.0  Nairobi         Mary  2025-01-05
107           Phone         NaN       4.0      NaN       Kelvin         NaN
72           Tablet       100.0       4.0   Kisumu        James         NaN
701             NaN      2000.0       1.0      NaN       Kelvin         NaN
21           Tablet      1200.0       3.0   Nakuru        Susan  2025-01-01
615          Tablet       500.0       2.0      NaN        James         NaN
122      Headphones       500.0       4.0      NaN        Brian  2025-01-01
467      Headphones         NaN       4.0      NaN        Susan         NaN

        total_price
sale_id
103          2400.0
436            None
271            None
107            None
72            400.0
701          2000.0
21           3600.0
615          1000.0
122          2000.0
467            None

,product,unit_price,quantity,region,sales_person,date,total_price
sale_id,,,,,,,
103,Headphones,1200.0,2.0,Kisumu,Brian,2025-01-01,2400.0
436,Headphones,150.0,NaN,None,Kelvin,None,NaN
271,Camera,None,3.0,Nairobi,Mary,2025-01-05,NaN
107,Phone,None,4.0,None,Kelvin,None,NaN
72,Tablet,100.0,4.0,Kisumu,James,None,400.0
701,None,2000.0,1.0,None,Kelvin,None,2000.0
21,Tablet,1200.0,3.0,Nakuru,Susan,2025-01-01,3600.0
615,Tablet,500.0,2.0,None,James,None,1000.0
122,Headphones,500.0,4.0,None,Brian,2025-01-01,2000.0
467,Headphones,None,4.0,None,Susan,None,NaN
215,Phone,50.0,1.0,None,Mary,2025-01-01,50.0
331,Tablet,1200.0,5.0,Nairobi,Mary,2025-01-05,6000.0
459,Tablet,150.0,2.0,Kisumu,Mary,None,300.0
88,Camera,50.0,NaN,Mombasa,Susan,2025-01-01,NaN
373,Headphones,50.0,3.0,Mombasa,Susan,Not Available,150.0

**Replacing missing values - On the entire dataframe**

---
We use **dropna(replacement)** function to replace missing values on our entire dataframe

In [49]:
#We decide that we should put "None" in the missing values with the hope that the sales people and the people responsible would
#provide the required data. The ones which we won't be able to get there data, we are going to drop them.

messy_sales_data.fillna("None", inplace=True)
messy_sales_data

/tmp/ipykernel_58986/2151527195.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'None' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  messy_sales_data.fillna("None", inplace=True)

,product,unit_price,quantity,region,sales_person,date,total_price
sale_id,,,,,,,
103,Headphones,1200.0,2.0,Kisumu,Brian,2025-01-01,2400.0
436,Headphones,150.0,None,None,Kelvin,None,None
271,Camera,None,3.0,Nairobi,Mary,2025-01-05,None
107,Phone,None,4.0,None,Kelvin,None,None
72,Tablet,100.0,4.0,Kisumu,James,None,400.0
...,...,...,...,...,...,...,...
157,None,150.0,None,Mombasa,None,Not Available,None
648,Laptop,500.0,None,Nakuru,James,None,None
261,Headphones,None,5.0,Mombasa,Kelvin,2025-01-05,None
157,Tablet,150.0,1.0,Kisumu,Mary,2025-01-05,150.0
47,Laptop,1200.0,3.0,Kisumu,Mary,None,3600.0

#### Fixing inconsistent values
---
* __Replacing inconsistent values__

In [50]:
# We can replace inconsistent
# creating a csv file with inconsistent data

data = {
    "product": ["Phone", "phone", "PHONE", "Tablet", "Tab", "tablet", None, "Laptop", "laptop", " LAPTOP "],
    "region": ["Nairobi", "nairobi ", "Nrb", "Mombasa", "mombasa", None, " Kisumu", "Kisumu", "KSM", "kIsUmU"],
    "quantity": [10, "12", None, 5, "five", 8, 3, "03", 7, ""],
    "unit_price": [25000, "25,000", 30000, None, "30k", 15000, "15000 ", 100000, "100 000", "100000"],
    "date": ["2024-01-02", "01/03/2024", "2024/01/04", "Jan 5 2024", None, "2024-13-01", "2024-02-30", "2024-02-10", "10-02-2024", "2024/2/9"],
    "total_price": [250000, "300000", None, "125,000", "", 200000, "200 000", "1000000", None, "1,000,000"]
}

df = pd.DataFrame(data)
file_path = "inconsistent_data.csv"
df.to_csv(file_path, index=False) #we have use index=False to avoid the index being saved as a column

In [51]:
incosistent_data = pd.read_csv("inconsistent_data.csv")
incosistent_data

    product    region quantity unit_price        date total_price
0     Phone   Nairobi       10      25000  2024-01-02      250000
1     phone  nairobi        12     25,000  01/03/2024      300000
2     PHONE       Nrb      NaN      30000  2024/01/04         NaN
3    Tablet   Mombasa        5        NaN  Jan 5 2024     125,000
4       Tab   mombasa     five        30k         NaN         NaN
5    tablet       NaN        8      15000  2024-13-01      200000
6       NaN    Kisumu        3     15000   2024-02-30     200 000
7    Laptop    Kisumu       03     100000  2024-02-10     1000000
8    laptop       KSM        7    100 000  10-02-2024         NaN
9   LAPTOP     kIsUmU      NaN     100000    2024/2/9   1,000,000

In [52]:
#Let's fix the product column
incosistent_data["product"]=incosistent_data["product"].str.strip()
incosistent_data["product"]=incosistent_data["product"].replace({"Tab":"Tablet"}).str.capitalize().astype(str)

#Let's fix the region column
incosistent_data["region"] = incosistent_data["region"].str.strip()
incosistent_data["region"] = incosistent_data["region"].replace({"Nrb":"Nairobi", "KSM":"Kisumu"}).str.capitalize().astype(str)
incosistent_data

#Let's fix the quantity column
incosistent_data["quantity"] = incosistent_data["quantity"].replace({"five":5, "03":3}).astype(float)
incosistent_data

#Let's fix the unit_price
incosistent_data ["unit_price"] = incosistent_data["unit_price"].replace(
    {"25,000":25000, "30k":30000, "100 000":100000}).astype(float)

#let's fix the date column
incosistent_data["date"] = incosistent_data["date"].str.strip()
incosistent_data["date"] = incosistent_data["date"].replace({
    "01/03/2024":"2024-03-01", 
    "2024/01/04":"2024-01-04",
    "Jan 5 2024":"2024-01-05",
    "2024-13-01":"2024-01-13",
    "10-02-2024":"2024-02-10",
    "2024/2/9":"2024-02-09"})

# incosistent_data["date"]= pd.to_datetime(incosistent_data["date"], errors="coerce")
# We will dive deep into date conversion later

#Let's fix the last column - total_price
incosistent_data["total_price"] = incosistent_data["total_price"].replace({
    "125,000":125000,
    "200 000":200000,
    "1,000,000":1000000}).astype(float)

incosistent_data

#We have successfully cleaned our data by replacing the inconsistent values with the write values, set the sentense case to be capitalized
#adhusted the dtype accordingly

#now, let's export our data as cleaned_incosistent_data.csv

incosistent_data.to_csv("cleaned_inconsistent_data.csv", index=False)
pd.read_csv("cleaned_inconsistent_data.csv")

  product   region  quantity  unit_price        date  total_price
0   Phone  Nairobi      10.0     25000.0  2024-01-02     250000.0
1   Phone  Nairobi      12.0     25000.0  2024-03-01     300000.0
2   Phone  Nairobi       NaN     30000.0  2024-01-04          NaN
3  Tablet  Mombasa       5.0         NaN  2024-01-05     125000.0
4  Tablet  Mombasa       5.0     30000.0         NaN          NaN
5  Tablet      NaN       8.0     15000.0  2024-01-13     200000.0
6     NaN   Kisumu       3.0     15000.0  2024-02-30     200000.0
7  Laptop   Kisumu       3.0    100000.0  2024-02-10    1000000.0
8  Laptop   Kisumu       7.0    100000.0  2024-02-10          NaN
9  Laptop   Kisumu       NaN    100000.0  2024-02-09    1000000.0

#### **String Standardiztion**
---

String standardization simply means **making text consistent** across a dataset so it is easier to clean, analyze, merge, or compare.

Think of it like “formatting all text to look the same.”

---

#### ✅ **In Data Cleaning (especially with Python), string standardization includes:**

#### **1. Lowercasing or uppercasing**

So that `"Kenya"`, `"kenya"`, and `"KENYA"` are treated the same.

```python
df["country"] = df["country"].str.lower()
```

---

#### **2. Removing extra spaces**

Cleaning `"  Nairobi "` → `"Nairobi"`.

```python
df["city"] = df["city"].str.strip()
```

---

#### **3. Removing multiple spaces between words**

`"Data    Science"` → `"Data Science"`

```python
df["text"] = df["text"].str.replace(r"\s+", " ", regex=True)
```

---

#### **4. Standardizing spelling variations**

* `"Mombasa"` vs `"Msa"`
* `"Nairobi"` vs `"Nrb"`
* `"Male"` vs `"M"`

We convert all of them into one version:

```python
df["city"] = df["city"].replace({
    "Msa": "Mombasa",
    "Mombas": "Mombasa",
    "Mombasa ": "Mombasa"
})
```

---

#### **5. Removing punctuation**

Cleaning names or product fields.

```python
df["name"] = df["name"].str.replace(r"[^\w\s]", "", regex=True)
```

---

#### **6. Replacing inconsistent formats**

Example: `"yes"`, `"Y"`, `"YES "`, `"y"` → all become `"yes"`.

---

#### **7. Converting to standardized patterns**

Example: phone numbers:
`"0792-752-985"` → `"0792752985"`

---

#### 📌 Why string standardization matters

Because datasets can’t be analyzed properly when:

* Nairobi ≠ nairobi
* Male ≠ M
* Ksh 1000 ≠ 1000
* “Product A ” ≠ “Product A” (because of trailing spaces)

It prevents:

* Wrong grouping
* Wrong counts
* Wrong merges
* Duplicate categories
* Failed joins in SQL/Pandas

---

#### 🎯 In short:

String standardization = **making all text consistent so your data becomes clean, uniform, and ready for analysis.**

---
**We are going to go deeper into practice in this especially the replace part after tackling advanced string manipulations - regex**

---

### **Removing duplictes**
---
We remove duplicates using the **drop_duplicates()** function.

In [53]:
#Let's remove duplicats in our financial data
messy_finance_data.drop_duplicates(inplace=True)
messy_finance_data.head(20)

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
91,Checking,200.0,Deposit,Failed,John,Invalid
601,Savings,4500.0,Transfer,Completed,Kim,Invalid
764,Checking,200.0,Withdrawal,Completed,Sarah,2025-02-01
755,Checking,200.0,Deposit,Pending,Alice,2025-02-01
479,Checking,3000.0,Withdrawal,Failed,Michael,2025-02-01
576,Checking,100.0,Withdrawal,Pending,Sarah,2025-02-01
64,Savings,4500.0,Transfer,Pending,John,Invalid
870,Savings,4500.0,Deposit,Completed,John,Invalid
164,Credit,3000.0,Transfer,Completed,John,2025-02-01
281,Savings,200.0,Withdrawal,Pending,Michael,Invalid
210,Savings,100.0,Transfer,Completed,Michael,Invalid
218,Savings,4500.0,Deposit,Completed,Sarah,2025-02-01
656,Credit,100.0,Deposit,Pending,John,Invalid
834,Checking,100.0,Transfer,Pending,John,2025-02-01
199,Checking,4500.0,Withdrawal,Completed,Alice,Invalid
533,Credit,200.0,Transfer,Completed,Michael,Invalid
200,Savings,200.0,Deposit,Completed,Michael,2025-02-01
58,Savings,100.0,Deposit,Completed,Kim,Invalid
848,Credit,100.0,Withdrawal,Failed,John,Invalid
840,Savings,3000.0,Withdrawal,Pending,John,Invalid

In [54]:
#Let's aslo remove duplicates in our sales data
messy_sales_data.drop_duplicates(inplace=True)
messy_finance_data.head(20)

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
91,Checking,200.0,Deposit,Failed,John,Invalid
601,Savings,4500.0,Transfer,Completed,Kim,Invalid
764,Checking,200.0,Withdrawal,Completed,Sarah,2025-02-01
755,Checking,200.0,Deposit,Pending,Alice,2025-02-01
479,Checking,3000.0,Withdrawal,Failed,Michael,2025-02-01
576,Checking,100.0,Withdrawal,Pending,Sarah,2025-02-01
64,Savings,4500.0,Transfer,Pending,John,Invalid
870,Savings,4500.0,Deposit,Completed,John,Invalid
164,Credit,3000.0,Transfer,Completed,John,2025-02-01
281,Savings,200.0,Withdrawal,Pending,Michael,Invalid
210,Savings,100.0,Transfer,Completed,Michael,Invalid
218,Savings,4500.0,Deposit,Completed,Sarah,2025-02-01
656,Credit,100.0,Deposit,Pending,John,Invalid
834,Checking,100.0,Transfer,Pending,John,2025-02-01
199,Checking,4500.0,Withdrawal,Completed,Alice,Invalid
533,Credit,200.0,Transfer,Completed,Michael,Invalid
200,Savings,200.0,Deposit,Completed,Michael,2025-02-01
58,Savings,100.0,Deposit,Completed,Kim,Invalid
848,Credit,100.0,Withdrawal,Failed,John,Invalid
840,Savings,3000.0,Withdrawal,Pending,John,Invalid

### **Sorting**
---

For dataframes, sorting can be achieved by using the **sort_values(by="column")**
function.

To sort data entries by specific column(s), we need to pass the column(s) to the function

---

1. **Ascending order**
---

* __dataframe.sort_vale(by="column")__

In [55]:
#Let's sort our financial data by the amount column
messy_finance_data.sort_values(by="amount")

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
622,Checking,100.0,Transfer,Failed,John,2025-02-01
236,Credit,100.0,Transfer,Completed,Alice,2025-02-01
798,Checking,100.0,Withdrawal,Failed,Sarah,Invalid
433,Credit,100.0,Transfer,Pending,Alice,Invalid
810,Savings,100.0,Deposit,Completed,Sarah,2025-02-01
...,...,...,...,...,...,...
615,Checking,4500.0,Withdrawal,Failed,Alice,Invalid
687,Savings,4500.0,Withdrawal,Completed,John,2025-02-01
790,Savings,4500.0,Withdrawal,Pending,Kim,Invalid
870,Savings,4500.0,Deposit,Completed,John,Invalid
199,Checking,4500.0,Withdrawal,Completed,Alice,Invalid

In [56]:
# let's sort our sales data by unit price and total price
messy_sales_data.sort_values(by= ["unit_price", "total_price"])

#Our data first be sorted by unit price then according to unit price, total price will be sorted.

,product,unit_price,quantity,region,sales_person,date,total_price
sale_id,,,,,,,
215,Phone,50.0,1.0,None,Mary,2025-01-01,50.0
398,None,50.0,1.0,None,Brian,None,50.0
796,Laptop,50.0,1.0,Nairobi,Kelvin,2025-01-05,50.0
473,Camera,50.0,1.0,Mombasa,Susan,None,50.0
416,Phone,50.0,1.0,Nairobi,Susan,Not Available,50.0
...,...,...,...,...,...,...,...
616,Tablet,None,1.0,Nakuru,Brian,Not Available,None
579,Headphones,None,None,Nakuru,Susan,None,None
289,None,None,3.0,Kisumu,Mary,2025-01-01,None
196,Laptop,None,4.0,Nakuru,James,None,None
261,Headphones,None,5.0,Mombasa,Kelvin,2025-01-05,None

2. **Descending order**
---

* __dataframe.sort_value(by="column", ascending=False)__

In [57]:
#Let's start with our finance data, sort by amount in descending order
messy_finance_data.sort_values(by="amount", ascending=False)

,account_type,amount,transaction_type,status,client,timestamp
transaction_id,,,,,,
687,Savings,4500.0,Withdrawal,Completed,John,2025-02-01
663,Savings,4500.0,Transfer,Pending,Sarah,2025-02-01
401,Credit,4500.0,Deposit,Pending,Kim,2025-02-01
176,Savings,4500.0,Withdrawal,Completed,John,Invalid
199,Checking,4500.0,Withdrawal,Completed,Alice,Invalid
...,...,...,...,...,...,...
236,Credit,100.0,Transfer,Completed,Alice,2025-02-01
372,Checking,100.0,Deposit,Pending,John,Invalid
798,Checking,100.0,Withdrawal,Failed,Sarah,Invalid
622,Checking,100.0,Transfer,Failed,John,2025-02-01
506,Credit,100.0,Transfer,Failed,Kim,Invalid

In [58]:
#Let's now sort the sales data by unit price and total price in descending order
messy_sales_data.sort_values(by=["unit_price", "total_price"], ascending=False)

,product,unit_price,quantity,region,sales_person,date,total_price
sale_id,,,,,,,
271,Camera,None,3.0,Nairobi,Mary,2025-01-05,None
107,Phone,None,4.0,None,Kelvin,None,None
467,Headphones,None,4.0,None,Susan,None,None
131,Phone,None,None,None,None,None,None
662,None,None,2.0,Nairobi,James,None,None
...,...,...,...,...,...,...,...
511,Headphones,50.0,1.0,Nairobi,Mary,2025-01-05,50.0
673,Laptop,50.0,1.0,Nairobi,James,None,50.0
596,Headphones,50.0,1.0,None,Kelvin,2025-01-05,50.0
606,Laptop,50.0,1.0,None,Kelvin,None,50.0
78,Camera,50.0,1.0,Kisumu,Mary,2025-01-05,50.0

### Deleting columns and rows
---

Columns and rows can be deleted using the `drop()` function. 

The arguments are the **column name** or **row name** and the **axis** which should be:

- **1** if we are deleting **columns.**
- **0** if we are deleting **rows**.

---
1. **Deleting columns**
---

syntax: **dataframe.drop("column_name", axis=1)**

In [59]:
#Let's create a copy of the sales data to practice droping columns
sales_df_drop_sample = sales_data_df.copy()
sales_df_drop_sample

,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,1,Tablet,1989,8,Mombasa,James,15912
1,2,Headphones,403,7,Mombasa,James,2821
2,3,Tablet,1575,4,Kisumu,Brian,6300
3,4,Laptop,447,6,Nairobi,Brian,2682
4,5,Phone,637,5,Mombasa,James,3185
5,6,Laptop,453,4,Kisumu,Brian,1812
6,7,Laptop,1612,5,Kisumu,Mary,8060
7,8,Phone,834,7,Mombasa,Susan,5838
8,9,Laptop,923,7,Nairobi,Susan,6461
9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,11,Tablet,152,6,Nairobi,Brian,912
11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,13,Laptop,1345,2,Nakuru,Mary,2690
13,14,Tablet,878,3,Nakuru,Mary,2634
14,15,Laptop,736,6,Nairobi,Susan,4416
15,16,Tablet,1134,7,Nakuru,Brian,7938
16,17,Laptop,1108,7,Nakuru,Susan,7756
17,18,Camera,139,9,Kisumu,Mary,1251
18,19,Tablet,1240,6,Nairobi,James,7440
19,20,Tablet,481,2,Nairobi,Mary,962

In [60]:
#Let's say we wanted to drop the sales person column:
sales_df_drop_sample.drop("sales_person", axis=1, inplace=True)
sales_df_drop_sample

    sale_id     product  unit_price  quantity   region  total_price
0         1      Tablet        1989         8  Mombasa        15912
1         2  Headphones         403         7  Mombasa         2821
2         3      Tablet        1575         4   Kisumu         6300
3         4      Laptop         447         6  Nairobi         2682
4         5       Phone         637         5  Mombasa         3185
5         6      Laptop         453         4   Kisumu         1812
6         7      Laptop        1612         5   Kisumu         8060
7         8       Phone         834         7  Mombasa         5838
8         9      Laptop         923         7  Nairobi         6461
9        10      Camera        1021         3  Mombasa         3063
10       11      Tablet         152         6  Nairobi          912
11       12      Laptop         574         5   Nakuru         2870
12       13      Laptop        1345         2   Nakuru         2690
13       14      Tablet         878         3   Nakuru         2634
14       15      Laptop         736         6  Nairobi         4416
15       16      Tablet        1134         7   Nakuru         7938
16       17      Laptop        1108         7   Nakuru         7756
17       18      Camera         139         9   Kisumu         1251
18       19      Tablet        1240         6  Nairobi         7440
19       20      Tablet         481         2  Nairobi          962

In [61]:
#Let's sale we wanted to drop the unit price and region:
sales_df_drop_sample.drop(["unit_price", "region"], axis=1, inplace=True)
sales_df_drop_sample

    sale_id     product  quantity  total_price
0         1      Tablet         8        15912
1         2  Headphones         7         2821
2         3      Tablet         4         6300
3         4      Laptop         6         2682
4         5       Phone         5         3185
5         6      Laptop         4         1812
6         7      Laptop         5         8060
7         8       Phone         7         5838
8         9      Laptop         7         6461
9        10      Camera         3         3063
10       11      Tablet         6          912
11       12      Laptop         5         2870
12       13      Laptop         2         2690
13       14      Tablet         3         2634
14       15      Laptop         6         4416
15       16      Tablet         7         7938
16       17      Laptop         7         7756
17       18      Camera         9         1251
18       19      Tablet         6         7440
19       20      Tablet         2          962

---
2. **Deleting rows**
---

syntax: **dataframe.drop("row_name", axis=0)**

In [62]:
# Let's remove row 10 in our sales data
sales_df_drop_sample.drop(10, axis=0, inplace=True)
sales_df_drop_sample

    sale_id     product  quantity  total_price
0         1      Tablet         8        15912
1         2  Headphones         7         2821
2         3      Tablet         4         6300
3         4      Laptop         6         2682
4         5       Phone         5         3185
5         6      Laptop         4         1812
6         7      Laptop         5         8060
7         8       Phone         7         5838
8         9      Laptop         7         6461
9        10      Camera         3         3063
11       12      Laptop         5         2870
12       13      Laptop         2         2690
13       14      Tablet         3         2634
14       15      Laptop         6         4416
15       16      Tablet         7         7938
16       17      Laptop         7         7756
17       18      Camera         9         1251
18       19      Tablet         6         7440
19       20      Tablet         2          962

In [63]:
#Let's remove columns 5, 13, and 18
sales_df_drop_sample.drop([5, 13, 18], axis=0, inplace=True)
sales_df_drop_sample

    sale_id     product  quantity  total_price
0         1      Tablet         8        15912
1         2  Headphones         7         2821
2         3      Tablet         4         6300
3         4      Laptop         6         2682
4         5       Phone         5         3185
6         7      Laptop         5         8060
7         8       Phone         7         5838
8         9      Laptop         7         6461
9        10      Camera         3         3063
11       12      Laptop         5         2870
12       13      Laptop         2         2690
14       15      Laptop         6         4416
15       16      Tablet         7         7938
16       17      Laptop         7         7756
17       18      Camera         9         1251
19       20      Tablet         2          962

### **Transforming data**
---

The `.apply()` method in **pandas** is one of the most powerful tools for **transforming or manipulating data** in a DataFrame or Series.

---

#### **What `.apply()` does**

`.apply()` lets you **run a custom function on each row or column** (or on each element if it’s a Series).

It’s like saying:

> “Hey pandas, take every value (or row/column) here and do this thing to it.”

---

#### **1️⃣ Using `.apply()` on a Series (column)**

Example: Convert scores to grades:

In [64]:

data = {
    "name": ["Alice", "John", "Brenda", "David"],
    "score": [88, 75, 92, 60]
}

df = pd.DataFrame(data)

# Define a function
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    elif score >= 70:
        return "C"
    else:
        return "D"
    
df["grade"] = df["score"].apply(grade)
#We just pass the function as it is.
df

     name  score grade
0   Alice     88     B
1    John     75     C
2  Brenda     92     A
3   David     60     D

#### **2️⃣ Using `.apply()` with a lambda function**
---

You don’t always need to define a function separately:

In [65]:
df["score_plus5"]=df["score"].apply(lambda x:x + 5)
df

     name  score grade  score_plus5
0   Alice     88     B           93
1    John     75     C           80
2  Brenda     92     A           97
3   David     60     D           65


#### **3️⃣ Using `.apply()` on a DataFrame (row-wise or column-wise)**
---
You can apply a function across **rows** or **columns**:

```python


# Sum along each row (axis=1)
df["total"] = df.apply(lambda row: row["age"] + row["score"], axis=1)
print(df)
```

* `axis=1` → apply function **row-wise**
* `axis=0` → apply function **column-wise**

---

#### **When to use `.apply()`**

* Converting scores to grades
* Transforming text (capitalizing, removing spaces)
* Creating new columns from existing ones
* Applying custom calculations on rows

---

#### ⚡ **Quick tip**

* If your operation is **element-wise**, `.apply()` works great.
* But for **large datasets**, **vectorized operations** (like `df["score"] + 5`) are faster than `.apply()`.

---

In [66]:
# Example: sum age + score for each row
data = {"age": [20, 25, 30], "score": [80, 90, 70]}
df_2 = pd.DataFrame(data)
df_2

   age  score
0   20     80
1   25     90
2   30     70

In [67]:
df_2["total"] = df_2.apply(lambda row: row["age"] + row["score"], axis = 1)
df_2

   age  score  total
0   20     80    100
1   25     90    115
2   30     70    100

In [68]:
#Let's drop the total_price column in our sales data and recreate it again
sales_data_df = sales_data_df.drop("total_price", axis=1)
sales_data_df

    sale_id     product  unit_price  quantity   region sales_person
0         1      Tablet        1989         8  Mombasa        James
1         2  Headphones         403         7  Mombasa        James
2         3      Tablet        1575         4   Kisumu        Brian
3         4      Laptop         447         6  Nairobi        Brian
4         5       Phone         637         5  Mombasa        James
5         6      Laptop         453         4   Kisumu        Brian
6         7      Laptop        1612         5   Kisumu         Mary
7         8       Phone         834         7  Mombasa        Susan
8         9      Laptop         923         7  Nairobi        Susan
9        10      Camera        1021         3  Mombasa       Kelvin
10       11      Tablet         152         6  Nairobi        Brian
11       12      Laptop         574         5   Nakuru       Kelvin
12       13      Laptop        1345         2   Nakuru         Mary
13       14      Tablet         878         3   Nakuru         Mary
14       15      Laptop         736         6  Nairobi        Susan
15       16      Tablet        1134         7   Nakuru        Brian
16       17      Laptop        1108         7   Nakuru        Susan
17       18      Camera         139         9   Kisumu         Mary
18       19      Tablet        1240         6  Nairobi        James
19       20      Tablet         481         2  Nairobi         Mary

In [69]:
#Now, let's recreate it
sales_data_df["total_price"] = sales_data_df.apply(lambda row: row["unit_price"] * row["quantity"], axis=1)
sales_data_df

,sale_id,product,unit_price,quantity,region,sales_person,total_price
0,1,Tablet,1989,8,Mombasa,James,15912
1,2,Headphones,403,7,Mombasa,James,2821
2,3,Tablet,1575,4,Kisumu,Brian,6300
3,4,Laptop,447,6,Nairobi,Brian,2682
4,5,Phone,637,5,Mombasa,James,3185
5,6,Laptop,453,4,Kisumu,Brian,1812
6,7,Laptop,1612,5,Kisumu,Mary,8060
7,8,Phone,834,7,Mombasa,Susan,5838
8,9,Laptop,923,7,Nairobi,Susan,6461
9,10,Camera,1021,3,Mombasa,Kelvin,3063
10,11,Tablet,152,6,Nairobi,Brian,912
11,12,Laptop,574,5,Nakuru,Kelvin,2870
12,13,Laptop,1345,2,Nakuru,Mary,2690
13,14,Tablet,878,3,Nakuru,Mary,2634
14,15,Laptop,736,6,Nairobi,Susan,4416
15,16,Tablet,1134,7,Nakuru,Brian,7938
16,17,Laptop,1108,7,Nakuru,Susan,7756
17,18,Camera,139,9,Kisumu,Mary,1251
18,19,Tablet,1240,6,Nairobi,James,7440
19,20,Tablet,481,2,Nairobi,Mary,962

In [70]:
# We can also recreate it by.
total = sales_data_df["unit_price"] * sales_data_df["quantity"]
total

0     15912
1      2821
2      6300
3      2682
4      3185
5      1812
6      8060
7      5838
8      6461
9      3063
10      912
11     2870
12     2690
13     2634
14     4416
15     7938
16     7756
17     1251
18     7440
19      962
dtype: int64

In [71]:
#Let's say our amount in the finance data is in dollars and we wanted to convert it into kenyan shilling - dollar rate=129

financial_data_df["amount"] = financial_data_df["amount"].apply(lambda x: x*129)
financial_data_df

               account_type  amount transaction_type     status   client
transaction_id
1                    Credit  406737          Deposit     Failed    Sarah
2                   Savings  357330          Deposit     Failed     John
3                  Checking   85269          Deposit  Completed    Sarah
4                   Savings  187050          Deposit    Pending    Alice
5                  Checking  516645         Transfer     Failed    Sarah
6                    Credit  522063         Transfer    Pending      Kim
7                  Checking  384033          Deposit     Failed    Sarah
8                   Savings  466077       Withdrawal  Completed    Alice
9                  Checking  593142          Deposit  Completed     John
10                  Savings  453306          Deposit     Failed    Alice
11                  Savings   26574         Transfer     Failed    Sarah
12                 Checking  410736       Withdrawal    Pending  Michael
13                  Savings  126162          Deposit     Failed     John
14                 Checking  321855         Transfer     Failed      Kim
15                  Savings  220590       Withdrawal    Pending    Sarah
16                  Savings   13158         Transfer  Completed    Alice
17                  Savings  281865         Transfer  Completed    Alice
18                 Checking  515613         Transfer  Completed    Sarah
19                   Credit  108102          Deposit     Failed    Alice
20                 Checking  152736         Transfer     Failed  Michael

In [74]:
#To avoid having to get the csv file from the internet, let's download it instead
from downlod_csv_file import download_csv
download_csv(Animals = 'https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/Python/Animals.csv')

Downloaded successfully!!

In [73]:
animals_df = pd.read_csv("Animals.csv")
animals_df

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60,Grasslands,Vulnerable
1,Bengal Tiger,15,Forests,Endangered
2,Blue Whale,80,Ocean,Endangered
3,Giant Panda,20,Temperate Forest,Vulnerable
4,Komodo Dragon,30,Islands,Vulnerable
5,Polar Bear,25,Arctic,Vulnerable
6,Red Fox,5,Various,Least Concern
7,Emperor Penguin,20,Antarctic,Near Threatened
8,Koala,13,Eucalyptus Forests,Vulnerable
9,Orangutan,35,Rainforests,Critically Endangered
10,Snow Leopard,15,Mountain Ranges,Vulnerable
11,Bald Eagle,20,"Forests, Seacoasts",Least Concern
12,African Lion,14,Savanna,Vulnerable
13,Green Sea Turtle,80,"Oceans, Beaches",Endangered
14,Gray Wolf,8,"Forests, Tundra",Least Concern

* Using the `apply` and `lambda` functions, convert the `Average Lifespan (Years)` of all species into the float data type in `Long_lived_species`.

In [75]:
animals_df["Average Lifespan (Years)"] = animals_df["Average Lifespan (Years)"].apply(lambda x: float(x))
animals_df

,Species,Average Lifespan (Years),Habitat,Conservation Status
0,African Elephant,60.0,Grasslands,Vulnerable
1,Bengal Tiger,15.0,Forests,Endangered
2,Blue Whale,80.0,Ocean,Endangered
3,Giant Panda,20.0,Temperate Forest,Vulnerable
4,Komodo Dragon,30.0,Islands,Vulnerable
5,Polar Bear,25.0,Arctic,Vulnerable
6,Red Fox,5.0,Various,Least Concern
7,Emperor Penguin,20.0,Antarctic,Near Threatened
8,Koala,13.0,Eucalyptus Forests,Vulnerable
9,Orangutan,35.0,Rainforests,Critically Endangered
10,Snow Leopard,15.0,Mountain Ranges,Vulnerable
11,Bald Eagle,20.0,"Forests, Seacoasts",Least Concern
12,African Lion,14.0,Savanna,Vulnerable
13,Green Sea Turtle,80.0,"Oceans, Beaches",Endangered
14,Gray Wolf,8.0,"Forests, Tundra",Least Concern


Create a column `Threat Level` that categorises species into `High`, `Medium`, or `Low` based on their `Conservation Status`: 
- **High** for `Critically Endangered` and `Endangered` 
- **Medium** for `Vulnerable` and `Near Threatened`
- **Low** for `Least Concern`

In [76]:
def threat_level(conservation_status):
    if "Critically Endangered" and "Endangered" in conservation_status:
        return "High"
    elif "Vulnerable" and "Near Threatened" in conservation_status:
        return "Medium"
    else:
        return "Low"
    
animals_df["Threat level"] = animals_df["Conservation Status"].apply(threat_level)
animals_df

# OR
# def threat_level_2 (level):
#     if level in ["Critically Endangered", "Endangered"]:
#         return "High"
#     elif level in ["Vulnarable", "Near Threatened"]:
#         return "Medium"
#     else:
#         return "Low"

,Species,Average Lifespan (Years),Habitat,Conservation Status,Threat level
0,African Elephant,60.0,Grasslands,Vulnerable,Low
1,Bengal Tiger,15.0,Forests,Endangered,High
2,Blue Whale,80.0,Ocean,Endangered,High
3,Giant Panda,20.0,Temperate Forest,Vulnerable,Low
4,Komodo Dragon,30.0,Islands,Vulnerable,Low
5,Polar Bear,25.0,Arctic,Vulnerable,Low
6,Red Fox,5.0,Various,Least Concern,Low
7,Emperor Penguin,20.0,Antarctic,Near Threatened,Medium
8,Koala,13.0,Eucalyptus Forests,Vulnerable,Low
9,Orangutan,35.0,Rainforests,Critically Endangered,High
10,Snow Leopard,15.0,Mountain Ranges,Vulnerable,Low
11,Bald Eagle,20.0,"Forests, Seacoasts",Least Concern,Low
12,African Lion,14.0,Savanna,Vulnerable,Low
13,Green Sea Turtle,80.0,"Oceans, Beaches",Endangered,High
14,Gray Wolf,8.0,"Forests, Tundra",Least Concern,Low

### When to use DataFrames
Unlike the NumPy array which is suited for storing and performing computations on homogeneous data (data of the same type), Pandas DataFrames can accommodate heterogeneous data. This makes them the choice data structure for manipulating often messy data (for example, tabular data from spreadsheets, or SQL tables). 

We should use a Pandas DataFrame if all of the following statements hold:

* We have 2-dimensional data (rows and columns).
* The data type is the same within a column.
* We are interested in the index (rows) and column names.

Pandas DataFrames are especially beneficial for data manipulation tasks like merging, joining, and reshaping data.

Important notes

When creating a new column from a series, it can be of any length but when creating a column from a list, it must be of the same length as the data frame.

creating a column from a single value:

dataframe["new_column"] = 4

or 

car_sales["passed_road_test"] = True
 
A new column will be created with fours, and True - bools respectively